Passed the 6th param $includeDirectChildrenOnly class
scandipwa/catalog-graphql pull request #137
Opened 2022-05-05 12:31 UTC by AzizKHAN030

Got error in `localmodules/catalog-graphql/src/Model/Layer/Filter/Category.php` that in parent::__construct only 5 params were passed and in newer version it needs 6 params

- Passed the 6th param `$includeDirectChildrenOnly `class.

- Now I can get the product filters but I'm getting sort_fields as null and error for that issue

**Note**

- In my local the ` "scandipwa/performance": "^1.1.0",` in require block in composer.json  was changed to `"scandipwa/performance": "dev-master as 1.5.5",`

2022-05-05 18:08 UTC, zans-laksa approved these changes

2022-05-06 06:16 UTC, AzizKHAN030 commented
Changed the name of the class in `localmodules/catalog-graphql/src/SearchAdapter/Query/Builder/Match.php` because the className in magento was renamed to MatchQuery due to PHP8 reserved keywords

2022-05-06 14:58 UTC, zans-laksa approved these changes

2022-06-06 14:52 UTC, AzizKHAN030 commented
I think that this is a hotfix and pushing it in order to fix m244 instance, because there are too many errors in many pages.

2022-06-06 22:59 UTC, zans-laksa requested changes

2022-06-06 22:59 UTC, zans-laksa commented on src/Elasticsearch5/SearchAdapter/Aggregation/Interval.php
> +    private $connectionManager;
Please use the `protected` access modifiers instead of `private` in all your code.

2022-06-06 22:59 UTC, zans-laksa commented on src/Elasticsearch5/SearchAdapter/Aggregation/Interval.php
> +        $to = ['lt' => 0];
Please leave a descriptive commend and a link to the issue in order to describe the purpose of this override.
Same on all other methods you overridden, so we can see what actually changed.

2022-06-06 22:59 UTC, zans-laksa commented on src/Elasticsearch5/SearchAdapter/Aggregation/Interval.php
> +        if ($data) {
Please separate blocks with the new line here and in other places in the code too.

2022-06-09 17:31 UTC, carinadues commented
Commenting to follow up

2022-06-10 12:53 UTC, zans-laksa approved these changes

2022-06-10 23:56 UTC, merged