#4353 - Add category in magento tags
scandipwa/catalog-graphql pull request #138
Opened 2022-05-11 12:52 UTC by IrinaZhadzinets

**Related issue(s):**
* Fixes https://github.com/scandipwa/scandipwa/issues/4353

2022-05-11 14:39 UTC, AleksandrsKondratjevs commented on src/Model/Resolver/Products/Query/Search.php
> +    protected $categoryCollectionFactory;
CategoryCollectionFactory $categoryCollectionFactory

Same as name import as CategoryCollectionFactory.

2022-05-11 15:57 UTC, AleksandrsKondratjevs approved these changes

2022-05-11 19:08 UTC, zans-laksa requested changes

2022-05-11 19:08 UTC, zans-laksa commented on src/Model/Resolver/Products/Query/Search.php
> +            $this->categoryCollectionFactory->create()
Please add a detailed comment to explain what is happening here and the link to the task.

2022-05-12 10:09 UTC, zans-laksa approved these changes

2022-05-12 10:40 UTC, merged